name: Checks

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Check formatting on nix files in Toolbelt 🛠️
      run:  nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt . --check"

    - name: Shell check scripts 🐢
      run: .github/workflows/shellcheck.sh
